Repository rerun-io/re_mp4, pull requests merged in 2024-11, with the labels that each got.

#13 Update changelog-generation and RELEASES.md
  .github/workflows/cargo_machete.yml
  Cargo.lock
  Cargo.toml
  RELEASES.md
  scripts/generate_changelog.py
  scripts/template_update.py
Labels: exclude from changelog

#14 fix integer overflow when ctts contains entries with negative offsets
  src/reader.rs
Labels: bug, include in changelog

#15 Handle negative data_offset in TrunBox
  src/reader.rs
Labels: bug, include in changelog

#16 Account for video with DTS shift and resulting negative dts values
  src/reader.rs
Labels: enhancement, include in changelog

#17 Shift DTS & CTS by minimum CTS to mimick `ffprobe`'s behavior
  src/reader.rs
Labels: enhancement, include in changelog
